services:
  - type: web
    name: gipjazes-api-server
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_DPwZ7VNnCIL9@ep-aged-sky-amxwb0of-pooler.c-5.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require
      - key: REDIS_URL
        fromService:
          name: gipjazes-redis
          type: redis
          property: connectionString
      - key: CLOUDINARY_URL
        value: cloudinary://265858125732696:ZGNDDEn5nNDJu6OA19nnKgOpDNc@ddst0aipf

  - type: redis
    name: gipjazes-redis
    ipAllowList: []
