services:
  - type: web
    name: gipjazes-api-server
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_mWH4iehn3wku@ep-misty-frog-amra4cwk-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: REDIS_URL
        fromService:
          name: gipjazes-redis
          type: redis
          property: connectionString
      - key: CLOUDINARY_URL
        value: cloudinary://265858125732696:ZGNDDEn5nNDJu6OA19nnKgOpDNc@ddst0aipf

  - type: redis
    name: gipjazes-redis
    plan: free
    ipAllowList: []
