// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GIPJAZESService_Register_FullMethodName      = "/gipjazes.GIPJAZESService/Register"
	GIPJAZESService_Login_FullMethodName         = "/gipjazes.GIPJAZESService/Login"
	GIPJAZESService_GetFeed_FullMethodName       = "/gipjazes.GIPJAZESService/GetFeed"
	GIPJAZESService_GetUploadUrl_FullMethodName  = "/gipjazes.GIPJAZESService/GetUploadUrl"
	GIPJAZESService_AdminTakedown_FullMethodName = "/gipjazes.GIPJAZESService/AdminTakedown"
)

// GIPJAZESServiceClient is the client API for GIPJAZESService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GIPJAZESServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	GetUploadUrl(ctx context.Context, in *SignedUrlRequest, opts ...grpc.CallOption) (*SignedUrlResponse, error)
	AdminTakedown(ctx context.Context, in *TakedownRequest, opts ...grpc.CallOption) (*TakedownResponse, error)
}

type gIPJAZESServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGIPJAZESServiceClient(cc grpc.ClientConnInterface) GIPJAZESServiceClient {
	return &gIPJAZESServiceClient{cc}
}

func (c *gIPJAZESServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, GIPJAZESService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gIPJAZESServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, GIPJAZESService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gIPJAZESServiceClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, GIPJAZESService_GetFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gIPJAZESServiceClient) GetUploadUrl(ctx context.Context, in *SignedUrlRequest, opts ...grpc.CallOption) (*SignedUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedUrlResponse)
	err := c.cc.Invoke(ctx, GIPJAZESService_GetUploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gIPJAZESServiceClient) AdminTakedown(ctx context.Context, in *TakedownRequest, opts ...grpc.CallOption) (*TakedownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakedownResponse)
	err := c.cc.Invoke(ctx, GIPJAZESService_AdminTakedown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GIPJAZESServiceServer is the server API for GIPJAZESService service.
// All implementations must embed UnimplementedGIPJAZESServiceServer
// for forward compatibility.
type GIPJAZESServiceServer interface {
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	GetFeed(context.Context, *GetFeedRequest) (*FeedResponse, error)
	GetUploadUrl(context.Context, *SignedUrlRequest) (*SignedUrlResponse, error)
	AdminTakedown(context.Context, *TakedownRequest) (*TakedownResponse, error)
	mustEmbedUnimplementedGIPJAZESServiceServer()
}

// UnimplementedGIPJAZESServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGIPJAZESServiceServer struct{}

func (UnimplementedGIPJAZESServiceServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGIPJAZESServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGIPJAZESServiceServer) GetFeed(context.Context, *GetFeedRequest) (*FeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeed not implemented")
}
func (UnimplementedGIPJAZESServiceServer) GetUploadUrl(context.Context, *SignedUrlRequest) (*SignedUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadUrl not implemented")
}
func (UnimplementedGIPJAZESServiceServer) AdminTakedown(context.Context, *TakedownRequest) (*TakedownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminTakedown not implemented")
}
func (UnimplementedGIPJAZESServiceServer) mustEmbedUnimplementedGIPJAZESServiceServer() {}
func (UnimplementedGIPJAZESServiceServer) testEmbeddedByValue()                         {}

// UnsafeGIPJAZESServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GIPJAZESServiceServer will
// result in compilation errors.
type UnsafeGIPJAZESServiceServer interface {
	mustEmbedUnimplementedGIPJAZESServiceServer()
}

func RegisterGIPJAZESServiceServer(s grpc.ServiceRegistrar, srv GIPJAZESServiceServer) {
	// If the following call panics, it indicates UnimplementedGIPJAZESServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GIPJAZESService_ServiceDesc, srv)
}

func _GIPJAZESService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GIPJAZESServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GIPJAZESService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GIPJAZESServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GIPJAZESService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GIPJAZESServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GIPJAZESService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GIPJAZESServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GIPJAZESService_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GIPJAZESServiceServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GIPJAZESService_GetFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GIPJAZESServiceServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GIPJAZESService_GetUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GIPJAZESServiceServer).GetUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GIPJAZESService_GetUploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GIPJAZESServiceServer).GetUploadUrl(ctx, req.(*SignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GIPJAZESService_AdminTakedown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakedownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GIPJAZESServiceServer).AdminTakedown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GIPJAZESService_AdminTakedown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GIPJAZESServiceServer).AdminTakedown(ctx, req.(*TakedownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GIPJAZESService_ServiceDesc is the grpc.ServiceDesc for GIPJAZESService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GIPJAZESService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gipjazes.GIPJAZESService",
	HandlerType: (*GIPJAZESServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GIPJAZESService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GIPJAZESService_Login_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _GIPJAZESService_GetFeed_Handler,
		},
		{
			MethodName: "GetUploadUrl",
			Handler:    _GIPJAZESService_GetUploadUrl_Handler,
		},
		{
			MethodName: "AdminTakedown",
			Handler:    _GIPJAZESService_AdminTakedown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
